// Generated by scripts/generate-sync-manifest.mjs. Do not edit by hand.

export const SYNC_MANIFEST_SCHEMA_VERSION = 1 as const;
export const SYNC_MANIFEST_DEFAULT_CONFLICT_POLICY = "serverVersionCasWholeRecord" as const;
export const SYNC_MANIFEST_STORE_NAMES = [
  "games",
  "analysis",
  "game-summaries",
  "retro-results",
  "saved-review-puzzles",
  "studies",
  "practice-lines",
  "position-progress",
  "drill-attempts",
  "folders",
  "accounts",
  "puzzle-definitions",
  "puzzle-attempts",
  "puzzle-user-meta",
  "puzzle-user-perf",
  "puzzle-rating-history",
  "opening-collections",
  "opening-session",
  "opening-training-variations",
  "repertoire-sources",
  "repertoire-match-records",
  "repertoire-scan-runs",
  "settings",
] as const;
export const SYNC_ACCOUNT_IDENTITY_FIELDS = [
  "id",
  "platform",
  "username",
  "addedAt",
] as const;
export const SYNC_ACCOUNT_PROFILE_FIELDS = [
  "displayName",
  "category",
  "section",
  "order",
  "tags",
  "lifetimeBest",
] as const;
export const SYNC_ACCOUNT_PROFILE_CLOCK = "profileUpdatedAt" as const;
export const SYNC_ACCOUNT_CURSOR_FIELDS = [
  "lastSyncedAt",
  "newestGameTimestamp",
  "oldestGameTimestamp",
  "syncFilterKey",
] as const;
export const SYNC_ACCOUNT_CURSOR_CLOCK = "syncCursorUpdatedAt" as const;
